"""Render a bumper report as a GitHub-flavoured PR comment.

Mirrors the verdict-tier visual language of
``packages/sca/diff.py::render_pr_comment`` (🛑 Block / ⚠ Review
/ ✓ Clean) so operators reading mixed bumper + diff PR comments
see consistent styling.

Output shape:

  ### <label> — verdict-line

  | Total | Clean | Review | Block |
  |---|---|---|---|
  | N | N | N | N |

  <details open>
  <summary><b>Bump proposals</b></summary>

  | Kind | Locator | Current | Target | Verdict | Notes |
  ...

  </details>

  <sub>Generated by raptor-sca bump · suppress-only ...</sub>

Verdict-line tiers (same as diff renderer):

* **🛑 Block**: any candidate verdict==Block. Operator must NOT
  auto-merge these — the bumper itself refuses to ``--apply``
  them.
* **⚠ Review**: any candidate verdict==Review. Operator decides;
  the bumper won't auto-apply.
* **✓ Clean**: every candidate verdict==Clean. Safe to auto-
  merge if the project's policy allows.
* **✓ no bumps**: no candidates. Nothing to bump."""

from __future__ import annotations

from io import StringIO
from typing import List, Optional

from .orchestrator import (
    BumpReport, BumpResult,
    _VERDICT_BLOCK, _VERDICT_CLEAN, _VERDICT_REVIEW,
)


def render_pr_comment(
    report: BumpReport, *,
    repo_label: Optional[str] = None,
    truncate_table_at: int = 30,
) -> str:
    """Return the bumper report as GitHub-flavoured Markdown."""
    label = repo_label or "raptor-sca bump"
    n_block = sum(1 for r in report.results
                  if r.verdict == _VERDICT_BLOCK)
    n_review = sum(1 for r in report.results
                   if r.verdict == _VERDICT_REVIEW)
    n_clean = sum(1 for r in report.results
                  if r.verdict == _VERDICT_CLEAN)
    total = len(report.results)

    buf = StringIO()
    buf.write(f"### {label} — {_verdict_line(n_block, n_review, n_clean, total)}\n\n")

    # One-line summary table.
    buf.write("| Total | Clean | Review | Block |\n")
    buf.write("|---|---|---|---|\n")
    block_cell = f"**{n_block}**" if n_block else "0"
    review_cell = f"**{n_review}**" if n_review else "0"
    buf.write(
        f"| {total} | {n_clean} | {review_cell} | {block_cell} |\n\n"
    )

    if report.results:
        # Dedup by (kind, locator, current, target). Same shape
        # as the text-mode render_report so PR comment + terminal
        # output match.
        groups: "dict[tuple, List[BumpResult]]" = {}
        order: List[tuple] = []
        for r in report.results:
            key = (
                r.candidate.kind, r.candidate.locator,
                r.candidate.current_version, r.candidate.target_version,
            )
            if key not in groups:
                groups[key] = []
                order.append(key)
            groups[key].append(r)

        # Sort: Block-tier first so reviewers see the worst at
        # the top; Review next; Clean last.
        def _group_sort_key(key):
            verdict = groups[key][0].verdict
            return (-verdict, key)

        rows_to_show = sorted(order, key=_group_sort_key)[:truncate_table_at]
        truncated = len(order) > truncate_table_at

        buf.write("<details open>\n")
        buf.write(
            f"<summary><b>Bump proposals ({total})</b></summary>\n\n"
        )
        buf.write(
            "| Kind | Locator | Current | Target | Verdict | Notes |\n"
        )
        buf.write("|---|---|---|---|---|---|\n")
        for key in rows_to_show:
            group = groups[key]
            head = group[0]
            n_files = len(group)
            notes = _notes_for_group(head, n_files)
            buf.write(
                f"| {head.candidate.kind} "
                f"| `{head.candidate.locator}` "
                f"| `{head.candidate.current_version}` "
                f"| `{head.candidate.target_version}` "
                f"| {_verdict_label_md(head.verdict)} "
                f"| {notes} |\n"
            )
        if truncated:
            buf.write(
                f"\n_+{len(order) - truncate_table_at} more proposals_\n"
            )
        buf.write("</details>\n\n")

    if report.skipped:
        # Emit a collapsed-by-default <details> with the per-surface
        # locator + reason. Without this the operator reading the
        # PR comment sees only a count and has to re-run with -v to
        # learn what wasn't bumped (e.g. a Helm repo redirect, an
        # OCI registry tag-list 403, a malformed Chart.yaml).
        # Truncate to a sane cap so a project with hundreds of
        # skipped surfaces doesn't blow out the PR comment size limit.
        cap = 20
        buf.write(
            f"<details>\n<summary>"
            f"<i>Skipped: {len(report.skipped)} surface(s) "
            f"(upstream lookup failures / non-semver targets)</i>"
            f"</summary>\n\n"
        )
        for arg, path, reason in report.skipped[:cap]:
            buf.write(
                f"- `{arg}` ({path.name}): "
                f"{_truncate_one_line(reason, 240)}\n"
            )
        if len(report.skipped) > cap:
            buf.write(
                f"\n_+{len(report.skipped) - cap} more skipped_\n"
            )
        buf.write("</details>\n\n")

    buf.write(
        "\n<sub>Generated by raptor-sca bump · suggest-only — "
        "``--apply`` writes Clean bumps in place; Review / Block "
        "require human review.</sub>\n"
    )
    return buf.getvalue()


def _verdict_line(
    n_block: int, n_review: int, n_clean: int, total: int,
) -> str:
    """Compact verdict line for the comment header."""
    if total == 0:
        return "✓ no bumps available"
    if n_block:
        return (
            f"**🛑 {n_block} block-tier bump"
            f"{'s' if n_block != 1 else ''}** — "
            "supply-chain or CVE signal; do not auto-merge"
        )
    if n_review:
        return (
            f"**⚠ {n_review} review-tier bump"
            f"{'s' if n_review != 1 else ''}**"
            + (f" · {n_clean} clean" if n_clean else "")
        )
    return f"✓ {n_clean} clean bump{'s' if n_clean != 1 else ''} available"


def _verdict_label_md(verdict: int) -> str:
    """Verdict cell content with eye-magnet glyph."""
    if verdict == _VERDICT_BLOCK:
        return "🛑 **Block**"
    if verdict == _VERDICT_REVIEW:
        return "⚠ Review"
    return "✓ Clean"


def _truncate_one_line(text: str, max_len: int) -> str:
    """Collapse to one line and clip at ``max_len`` chars with an
    ellipsis when truncated. Newlines become spaces so a multi-line
    upstream-error message doesn't break a markdown list item or
    table row; surrounding whitespace is stripped."""
    flat = " ".join(text.split())
    if len(flat) <= max_len:
        return flat
    return flat[: max_len - 1].rstrip() + "…"


def _notes_for_group(head: BumpResult, n_files: int) -> str:
    """Pack the per-group notes into one comment cell.

    Surfaces:
    * supply-chain finding kinds (recent_publish, maintainer_change,
      install_hook_suspicious) — explains WHY a Review verdict.
    * Newly-introduced CVE IDs from the vuln-delta — explains WHY
      a Block verdict.
    * File count when >1 (deduped across files).
    """
    bits: List[str] = []
    for sf in head.bump_supply_chain_findings:
        bits.append(sf.kind)
    for vf in head.bump_vuln_findings:
        adv = vf.advisories[0] if vf.advisories else None
        cve_id = (adv.osv_id if adv else "?")
        kev = " (KEV)" if vf.in_kev else ""
        bits.append(f"new-CVE `{cve_id}`{kev}")
    if n_files > 1:
        bits.append(f"{n_files} files")
    if head.rewrite_result is not None and head.rewrite_result.applied:
        bits.append("applied")
    if head.error:
        bits.append(f"error: {head.error}")
    return " · ".join(bits) if bits else "—"
