"""Data model for the /sca pipeline.

Every signal in the pipeline carries a Confidence; every finding has a single
canonical schema; risk is surfaced as components only (no composite score
yet — see ~/design/sca.md § Risk components).

All dataclasses are JSON-serialisable via dataclasses.asdict; the report and
findings.json layers handle that wrapping.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Any, Dict, List, Literal, Optional


# ---------------------------------------------------------------------------
# Confidence — cross-cutting uncertainty type
# ---------------------------------------------------------------------------

ConfidenceLevel = Literal["low", "medium", "high"]

# Standard categorical → numeric mapping. Used wherever a level is given
# without an explicit numeric override.
_CONFIDENCE_NUMERIC = {"low": 0.30, "medium": 0.70, "high": 0.95}


@dataclass(frozen=True)
class Confidence:
    """Cross-cutting confidence/uncertainty for any signal in the pipeline.

    Carries:
      - level: human-readable bucket
      - numeric: 0.0-1.0 for the (future) risk-score formula
      - reason: max-200-char human-readable justification

    The standard level→numeric mapping (low=0.30, medium=0.70, high=0.95) is
    applied when numeric is not explicitly provided. Pass an explicit numeric
    when a signal is genuinely continuous (e.g., wrapping EPSS directly).
    """

    level: ConfidenceLevel
    reason: str = ""
    numeric: Optional[float] = None

    def __post_init__(self) -> None:
        if self.numeric is None:
            object.__setattr__(self, "numeric", _CONFIDENCE_NUMERIC[self.level])
        if len(self.reason) > 200:
            object.__setattr__(self, "reason", self.reason[:197] + "...")


# ---------------------------------------------------------------------------
# Pin style — how tightly a manifest declares a version
# ---------------------------------------------------------------------------

class PinStyle(str, Enum):
    EXACT = "exact"          # ==1.2.3
    CARET = "caret"          # ^1.2.3 (npm: compatible-with)
    TILDE = "tilde"          # ~1.2.3 (npm: approximately)
    RANGE = "range"          # >=1.2.0,<2.0.0
    WILDCARD = "wildcard"    # *
    GIT = "git"              # git+https://... or git ref
    PATH = "path"            # local path
    UNKNOWN = "unknown"      # parser couldn't classify


# ---------------------------------------------------------------------------
# Dependency — one row per dep (direct or transitive)
# ---------------------------------------------------------------------------

@dataclass
class Dependency:
    """A single dep observed in a manifest or lockfile."""

    ecosystem: str               # "Maven", "PyPI", "npm", "Cargo", "Go",
                                 # "RubyGems", "NuGet", "Packagist"
    name: str                    # canonical (purl-ready), case-normalised
    version: Optional[str]       # None = unpinned manifest entry
    declared_in: Path            # which manifest/lockfile observed it
    scope: str                   # "main" | "dev" | "test" | "peer" |
                                 # "optional" | "build"
    is_lockfile: bool            # True if from a lockfile (resolved version)
    pin_style: PinStyle
    direct: bool                 # True if declared, False if transitive
    purl: str                    # pkg:maven/group/artifact@version
    parser_confidence: Confidence  # exact (POM XML) | heuristic (Gradle DSL)
    declared_license: Optional[str] = None  # SPDX expr; SBOM use only
    commented_out: bool = False    # True when extracted from a commented
                                    # line (e.g. `# z3-solver==4.16.0.0`); the
                                    # findings layer downgrades severity to
                                    # info and the rewriter preserves the `#`
    source_kind: str = "manifest"   # "manifest" / "lockfile" / "dockerfile"
                                    # / "devcontainer" / "shell_script" /
                                    # "gha_workflow" / "cascade_resolver"
                                    # / "metadata_walk" / "review" /
                                    # "dockerfile_from" / "override" — feeds
                                    # the report's "where did this come
                                    # from" column. ``cascade_resolver`` is
                                    # a transitive dep generated by an
                                    # in-sandbox cascade run; ``metadata_walk``
                                    # is a transitive dep approximated by
                                    # registry-metadata recursion (less
                                    # accurate); ``review`` is operator-
                                    # supplied to ``raptor-sca check``.
    source_extra: Optional[Dict[str, Any]] = None
                                    # Per-source diagnostic context.
                                    # Examples:
                                    #   ``dockerfile_from`` rows carry
                                    #     ``{"image": "<ref>", "digest":
                                    #     "<sha256:...>", "stage_name":
                                    #     "builder" | None}`` so the
                                    #     report can group by base image
                                    #     and surface which build stage a
                                    #     finding came from.
                                    # Renderers that don't consume the
                                    # field treat it as a black box.
    workspace_root: Optional[Path] = None  # set when this dep was
                                            # parsed from a npm / Yarn /
                                            # pnpm workspace member; the
                                            # path of the monorepo root
                                            # (where the parent
                                            # ``package.json`` with the
                                            # ``workspaces`` field lives,
                                            # or where ``pnpm-workspace.yaml``
                                            # lives). Hygiene checks
                                            # group multi-workspace
                                            # findings under one logical
                                            # project; cross-workspace
                                            # divergent-version findings
                                            # use this as the cluster
                                            # key.

    version_floor: Optional[str] = None     # tightest lower bound
                                            # (``>=`` / ``>``) from the
                                            # original specifier — the
                                            # downgrade floor harden
                                            # honours when remediating
                                            # below the current pin.
    version_ceiling: Optional[str] = None   # tightest upper bound
                                            # (``<`` / ``<=``) — the
                                            # upgrade ceiling.

    def key(self) -> str:
        """Stable identity for dedup / cross-reference."""
        return f"{self.ecosystem}:{self.name}@{self.version or '*'}"


# ---------------------------------------------------------------------------
# Advisory — OSV / GHSA record matched to a dep
# ---------------------------------------------------------------------------

@dataclass
class AffectedRange:
    """One range entry from OSV's affected[].ranges[]."""

    type: Literal["SEMVER", "ECOSYSTEM", "GIT"]
    events: List[Dict[str, str]]  # [{"introduced": "0"}, {"fixed": "2.17.1"}]
    repo: Optional[str] = None    # for type=GIT


@dataclass
class CVSSScore:
    """Standard CVSS3.1 score + vector."""

    score: float                 # 0.0-10.0
    vector: str                  # "CVSS:3.1/AV:N/AC:L/..."
    severity: Literal["none", "low", "medium", "high", "critical"]


@dataclass
class Advisory:
    """A single OSV / GHSA / PYSEC advisory."""

    osv_id: str                  # "GHSA-jfh8-c2jp-5v3q" or "PYSEC-2024-..."
    aliases: List[str]           # ["CVE-2021-44228", ...]
    summary: str                 # one-line summary
    details: str                 # full markdown details (length-bounded)
    affected: List[AffectedRange]
    severity: Optional[CVSSScore]
    fixed_versions: List[str]    # extracted from affected.ranges.events.fixed
    references: List[str]        # URLs
    published: Optional[datetime] = None
    modified: Optional[datetime] = None
    ecosystem_specific: Optional[Dict[str, Any]] = None
    # ecosystem_specific.imports[].symbols populated for Go advisories;
    # used by Go function-level reachability.
    # RUSTSEC ``informational`` tag (and similar non-security markers
    # on other ecos). Values seen in the wild: ``"unsound"``,
    # ``"unmaintained"``, ``"notice"``. When set, the advisory is NOT
    # a security vulnerability — it's a soundness / quality concern
    # the upstream curators wanted to surface. Consumers (calibration
    # validate / refit; future: scan-time severity gating) skip these
    # from exploitation ground-truth so they don't inflate the
    # signal set. ``None`` for advisories that are real
    # vulnerabilities (vast majority).
    informational: Optional[str] = None


# ---------------------------------------------------------------------------
# Reachability — module-level (default) + Go function-level
# ---------------------------------------------------------------------------

ReachabilityVerdict = Literal[
    "not_evaluated",   # parser doesn't support this ecosystem's import detection
    "not_reachable",   # dep is in tree but no import found in non-test source
    "imported",        # at least one import found in non-test source
    "not_function_reachable",  # imported, but the OSV-listed affected function(s)
                       # aren't called by the project (function-level resolver
                       # — currently PyPI when OSV ships affected_functions)
    "called_in_dead_code",     # vulnerable function called from project source,
                       # but EVERY call site lives in a project function with
                       # no callers (1-hop empty AND reverse closure empty).
                       # The vulnerable code path isn't exercised at runtime
                       # under normal use. Confidence is ``medium`` not
                       # ``high`` — a no-caller host might still be an entry
                       # point we can't see (CLI main, HTTP handler registered
                       # via decorator, pytest fixture, ``__main__`` module,
                       # packaging entry-point). Operators viewing medium
                       # confidence can override.
    "likely_called",   # vulnerable function/symbol confirmed at a call site
                       # in a project function that IS reachable — the call
                       # sits on a live execution path. (Go function-level
                       # when OSV ships symbols; PyPI function-level via
                       # core.inventory.reachability)
]


@dataclass
class Reachability:
    verdict: ReachabilityVerdict
    confidence: Confidence
    evidence: List[str] = field(default_factory=list)  # file:line refs


# Operator-facing display labels for each verdict. Title-cased for the
# rendered tables (the schema enum stays snake_case for the JSON/CLI
# contract). Single source of truth — renderers + reports import from
# here so a new verdict only needs one update.
REACHABILITY_LABELS: dict[str, str] = {
    "likely_called": "Likely called",
    "imported": "Imported",
    "called_in_dead_code": "Called in dead code",
    "not_reachable": "Not reachable",
    "not_function_reachable": "Not function reachable",
    "not_evaluated": "Not evaluated",
}

# Display order for breakdown tables: reachable-tier first, then
# uncertain, then not-reachable. Matches the triage-by-impact ordering
# operators want at a glance. New verdicts not in this tuple sort to
# the end (renderers handle the leftover set).
REACHABILITY_ORDER: tuple[str, ...] = (
    "likely_called",
    "imported",
    "called_in_dead_code",
    "not_reachable",
    "not_function_reachable",
    "not_evaluated",
)


# ---------------------------------------------------------------------------
# Findings — every finding flows into the shared findings.json schema
# ---------------------------------------------------------------------------

Severity = Literal["info", "low", "medium", "high", "critical"]


@dataclass
class VulnFinding:
    """sca:vulnerable_dependency — a known CVE/GHSA matches a dep."""

    finding_id: str              # stable, deterministic; used in cross-refs
    dependency: Dependency
    advisories: List[Advisory]
    in_kev: bool                 # CISA known-exploited
    epss: Optional[float]        # FIRST.org probability, 0.0-1.0
    fixed_version: Optional[str] # smallest fix
    reachability: Reachability
    version_match_confidence: Confidence
    cvss_score: Optional[float]  # max across advisories
    cvss_vector: Optional[str]
    severity: Severity
    exposure_factor: float       # 0.0-1.0; call-site density
    transitive_depth: int        # 0 = direct, N = N levels deep
    # Composite risk estimate (0..100) per the formula in
    # ``packages/sca/risk.py``. Calibration is unverified — see that
    # module for the status. ``risk_components`` carries the per-
    # multiplier breakdown so operators can read off "why is this
    # score what it is" without re-deriving it.
    raptor_risk_estimate: Optional[float] = None
    risk_components: Optional[Dict[str, Any]] = None
    # Exploit-existence evidence from the calibration corpus.
    # Augments ``in_kev`` with concrete references operators can
    # follow up on (Exploit-DB entry IDs, Metasploit module paths).
    # None when the corpus hasn't been loaded; an empty
    # ExploitEvidence (all-fields-empty) when loaded but no
    # signals matched any of this finding's CVE aliases.
    exploit_evidence: Optional["ExploitEvidence"] = None
    # CISA Vulnrichment SSVC `Exploitation` decision — one of
    # ``"active"`` / ``"poc"`` / ``"none"`` / ``None``. Closes the
    # cold-start eco gap where KEV / EPSS / EDB / MSF / PoC return
    # nothing for ~95% of Cargo / NuGet / Packagist findings;
    # Vulnrichment scores ~60% of those CVEs. ``active`` is a
    # KEV-equivalent signal (broader coverage than CISA KEV
    # itself); ``poc`` is an ExploitEvidence-equivalent signal.
    # ``None`` means either CISA hasn't enriched the CVE yet, or
    # the Vulnrichment lookup wasn't wired into this run.
    ssvc_exploitation: Optional[str] = None
    # SSVC ``Automatable`` decision — one of ``"yes"`` /
    # ``"no"`` / ``None``. Indicates whether the steps of an
    # attack can be reliably automated (think: wormable
    # potential, mass-scanning feasibility). Independent of
    # ``Exploitation``: a CVE can be poc + automatable=yes
    # (high-fanout exploitation likely) OR active + automatable
    # =no (skilled-actor-only). The risk formula applies a small
    # bonus multiplier on top of the SSVC tier when both
    # Exploitation>=poc AND Automatable=yes hold.
    ssvc_automatable: Optional[str] = None
    related_findings: List[str] = field(default_factory=list)
    suppressed: bool = False
    suppression_reason: Optional[str] = None


@dataclass(frozen=True)
class ExploitEvidence:
    """Per-CVE exploit-existence signals derived from the
    calibration corpus.

    All three sources are independent: a CVE can be in KEV without
    a public PoC, or have a public PoC without a Metasploit module,
    etc. Operators triaging vulns benefit from seeing all three.
    """
    kev_listed: bool = False
    edb_ids: List[int] = field(default_factory=list)
    msf_modules: List[str] = field(default_factory=list)
    github_poc_urls: List[str] = field(default_factory=list)

    @property
    def has_any(self) -> bool:
        """True iff at least one signal fired."""
        return (
            self.kev_listed
            or bool(self.edb_ids)
            or bool(self.msf_modules)
            or bool(self.github_poc_urls)
        )


HygieneKind = Literal[
    "lockfile_missing",
    "lockfile_drift",
    "unpinned_dependency",
    "loose_pin",
    "cross_manifest_inconsistency",
    "platform_compat",
    "yanked_version",
]


@dataclass
class HygieneFinding:
    """Security-relevant integrity issues only.

    Pure dev-quality (duplicate_versions, git_dependency, path_dependency,
    dead_dependency) is recorded as SBOM metadata, not findings.
    """

    finding_id: str
    kind: HygieneKind
    dependency: Dependency
    detail: str
    severity: Severity
    confidence: Confidence
    related_findings: List[str] = field(default_factory=list)
    suppressed: bool = False
    suppression_reason: Optional[str] = None


LicenseKind = Literal[
    "license_denied",       # dep's SPDX matches policy.deny
    "license_warned",       # dep's SPDX matches policy.warn
    "license_unknown",      # registry didn't return a license, can't enforce
    "license_incompatible", # multi-license expr with no acceptable choice
]


@dataclass
class LicenseFinding:
    """Per-dep license-policy finding — the legal/compliance dimension.

    Distinct from HygieneFinding (security integrity) and
    SupplyChainFinding (registry-level supply-chain attacks); a
    deny-listed license isn't a security issue, it's a compliance
    issue, and operators triage these on a different axis.
    """
    finding_id: str
    kind: LicenseKind
    dependency: Dependency
    spdx: Optional[str]              # the license string we evaluated; None on unknown
    detail: str
    severity: Severity
    confidence: Confidence
    suppressed: bool = False
    suppression_reason: Optional[str] = None


SupplyChainKind = Literal[
    "typosquat_candidate",
    "typosquat_domain",
    "recent_publish",
    "version_publish",
    "maintainer_change",
    "maintainer_account_change",
    "low_bus_factor",
    "install_hook_suspicious",
    "binary_in_tests",
    "large_obfuscated_artefact",
    "disguised_filename",
    "known_exfil_destination",
    "python_pth_file",
    "python_import_time_execution",
    "git_tag_drift",
    "gha_action_ref_drift",
    "gha_action_sunset",
    "gha_action_outdated",
    "version_diff_anomaly",
    "sentinel_match",
    "platform_compat_regression",
    "platform_compat_improvement",
    "transitive_now_optional",
    "binary_capability_delta",
    "image_capability_drift",
    "orphan_commit_dep",
    "payload_size_spike",
    "workflow_unsigned_commit",
    "branch_protection_missing_signed_commits",
    "slopsquat_suspect",
]


@dataclass
class SupplyChainFinding:
    """Supply-chain heuristic — mechanical or LLM-assisted."""

    finding_id: str
    kind: SupplyChainKind
    dependency: Dependency
    detail: str
    evidence: Dict[str, Any]     # raw signals (sanitised before display)
    severity: Severity
    confidence: Confidence
    related_findings: List[str] = field(default_factory=list)
    suppressed: bool = False
    suppression_reason: Optional[str] = None


# ---------------------------------------------------------------------------
# Risk metadata — NOT findings; inputs to risk and triage context
# ---------------------------------------------------------------------------

@dataclass
class RiskMetadata:
    """Risk-context signals — NOT findings.

    Operators don't 'fix' a heavy dep tree or large maintainer count — those
    are facts about the project's supply-chain shape. They flow into risk
    score components and triage prompt context, but never appear as findings.
    """

    dependency: Dependency
    transitive_count: int        # > N triggers triage-context note
    call_site_count: int         # blast radius if compromised
    unique_maintainers_in_tree: int
    max_tree_depth: int


# ---------------------------------------------------------------------------
# Triage — LLM ranking output
# ---------------------------------------------------------------------------

PriorityBucket = Literal["fix_today", "this_sprint", "this_quarter", "accept"]


@dataclass
class TriageItem:
    finding_id: str              # must match an emitted finding's ID
    rank: int                    # 1..N
    priority_bucket: PriorityBucket
    one_line_rationale: str      # max 200 chars
    confidence: Confidence


# ---------------------------------------------------------------------------
# Manifest — discovery output
# ---------------------------------------------------------------------------

@dataclass
class Manifest:
    """A discovered manifest or lockfile to be parsed."""

    path: Path                   # absolute path
    ecosystem: str               # which parser handles it
    is_lockfile: bool
    workspace_root: Optional[Path] = None
    # Set when this manifest is a workspace member; used to qualify
    # cross_manifest_inconsistency (deps differing across manifests
    # within a workspace are intentional, not a finding).
