"""Helm ``Chart.yaml`` dependency-version in-place rewriter.

Bumper-orchestrator emits :class:`RewriteEdit` with
``locator = chart_name`` (e.g. ``"postgresql"``); the rewriter
finds the dependency block under ``dependencies:`` whose
``name:`` matches the locator and rewrites that block's
``version:`` field.

The rewrite is line-shape-based (regex, not YAML parse+round-
trip) so the surrounding formatting / comments / indentation
stay intact — important because operator-edited Chart.yaml files
often have alignment and operator-comments that round-tripping
through ``yaml.safe_dump`` would destroy."""

from __future__ import annotations

import logging
import re
from pathlib import Path
from typing import List

from . import RewriteEdit, RewriteResult, register

logger = logging.getLogger(__name__)


def _is_chart_yaml(path: Path) -> bool:
    """Match ``Chart.yaml`` exactly (not ``Chart.lock`` — the
    lockfile gets regenerated by ``helm dep update`` after we
    bump Chart.yaml)."""
    return path.name == "Chart.yaml"


@register(predicate=_is_chart_yaml)
def rewrite_chart_yaml(
    path: Path, edits: List[RewriteEdit],
) -> List[RewriteResult]:
    """Apply chart-version edits to a Chart.yaml in place."""
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as e:
        return [RewriteResult(edit=e2, applied=False,
                              reason=f"error: read failed: {e}")
                for e2 in edits]

    new_text = text
    results: List[RewriteResult] = []
    for edit in edits:
        new_text, result = _apply_one_chart(new_text, edit)
        results.append(result)

    if any(r.applied for r in results):
        try:
            _atomic_write(path, new_text)
        except OSError as e:
            return [RewriteResult(edit=r.edit, applied=False,
                                  reason=f"error: write failed: {e}")
                    for r in results]
    return results


def _apply_one_chart(
    text: str, edit: RewriteEdit,
) -> "tuple[str, RewriteResult]":
    """Apply one chart-version edit.

    Strategy: find ``- name: <locator>`` inside the
    ``dependencies:`` block, then walk forward to find the
    matching ``version:`` line at the same indent. This
    side-steps YAML's "what's the next list item" ambiguity by
    finding both lines syntactically (regex) rather than
    structurally (yaml parse).
    """
    locator = re.escape(edit.locator)
    # Match ``- name: <locator>`` line then the following
    # ``version: <value>`` line at the same indent. The two
    # lines may appear in either order within the dep block;
    # try both shapes.
    #
    # Shape A: name-then-version
    pat_name_first = re.compile(
        rf"^(?P<indent>\s+)- name:\s*{locator}\s*\n"   # locator line
        rf"(?P<between>(?:\s*(?!-).+\n)*?)"             # optional intermediate lines
        rf"(?P<prefix>(?P=indent)\s+version:\s*[\"']?)"
        rf"(?P<ver>[^\s\"'#]+)"
        rf"(?P<suffix>[\"']?\s*(?:#[^\n]*)?\n)",
        re.MULTILINE,
    )
    # Shape B: version-then-name
    pat_version_first = re.compile(
        rf"^(?P<indent>\s+)- version:\s*[\"']?(?P<ver>[^\s\"'#]+)"
        rf"[\"']?\s*(?:#[^\n]*)?\n"
        rf"(?P<between>(?:\s*(?!-).+\n)*?)"
        rf"(?P=indent)\s+name:\s*{locator}\s*\n",
        re.MULTILINE,
    )
    match = pat_name_first.search(text)
    shape = "name_first"
    if match is None:
        match = pat_version_first.search(text)
        shape = "version_first"
    if match is None:
        return text, RewriteResult(
            edit=edit, applied=False, reason="not_found",
        )
    current_ver = match.group("ver")
    if current_ver == edit.new_value:
        return text, RewriteResult(
            edit=edit, applied=False, reason="no_change",
        )
    if current_ver != edit.old_value:
        return text, RewriteResult(
            edit=edit, applied=False,
            reason=(
                f"value_mismatch: file has {current_ver!r}, "
                f"plan expected {edit.old_value!r}"
            ),
        )
    if shape == "name_first":
        new_text = pat_name_first.sub(
            (
                rf"\g<indent>- name: {edit.locator}\n"
                rf"\g<between>"
                rf"\g<prefix>{edit.new_value}\g<suffix>"
            ),
            text, count=1,
        )
    else:
        new_text = pat_version_first.sub(
            (
                rf"\g<indent>- version: {edit.new_value}\n"
                rf"\g<between>"
                rf"\g<indent>  name: {edit.locator}\n"
            ),
            text, count=1,
        )
    return new_text, RewriteResult(
        edit=edit, applied=True, reason="applied",
    )


def _atomic_write(path: Path, content: str) -> None:
    """Atomic tempfile + rename (shared pattern with other
    rewriters)."""
    try:
        from .._atomic import atomic_write_text
        atomic_write_text(path, content)
        return
    except ImportError:
        pass
    import os
    import tempfile
    fd, tmp = tempfile.mkstemp(
        dir=str(path.parent), prefix=f".{path.name}.", suffix=".tmp",
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(content)
        os.replace(tmp, str(path))
    except Exception:                # noqa: BLE001
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise
