"""Witness data model — typed records for triggering inputs.

A ``Witness`` is the canonical record that captures the bytes a
pipeline observed (or attempted) triggering a bug with. Different
producers populate different optional fields; the type is
deliberately permissive so a v1 wrapping of (say) a fuzz crash
doesn't need to invent ASan metadata it doesn't have.

Stable contract for downstream consumers (reporting, ZKPoX
eventual consumer, calibrated IntentMatchJudge):

  * ``bytes_hash`` is the SHA-256 hex digest of the actual bytes,
    used as the lookup key in :class:`~core.witness.store.WitnessStore`.
  * ``source`` names which pipeline produced the record, so
    consumers can filter by provenance (e.g. "only show me
    fuzzer-verified witnesses").
  * ``observed_outcome`` is a normalised label across pipelines;
    pipeline-specific detail goes into ``outcome_detail``.
  * ``target_binary_hash`` / ``target_source_hash`` bind the
    witness to a specific build of the target; future re-runs can
    verify the binding before claiming a verdict still holds.

Witnesses are immutable once recorded — re-running the same input
against the same target produces a *new* Witness with a different
timestamp, not an in-place mutation of the original.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Optional


class WitnessSource(str, Enum):
    """Which pipeline produced this witness.

    Subclass of ``str`` so ``Witness.source`` serialises as a plain
    string in JSON output without a custom encoder.
    """

    # AFL++ generated bytes mutate-and-execute, surfaced as a crash
    # in the fuzzer's corpus.
    FUZZ = "fuzz"

    # /crash-analysis replayed an existing fuzz crash under gdb/rr,
    # observing it with debugger instrumentation. The bytes are the
    # same as the underlying fuzz crash; the value-add is the richer
    # outcome metadata (stack hash, crash address, etc.).
    CRASH_REPLAY = "crash_replay"

    # /validate Stage A / Stage B built a PoC, sandbox-ran it, and
    # observed the result. Bytes are the PoC's input shape (often
    # constructed by the LLM following the skill's instructions).
    VALIDATE_SKILL_POC = "validate_skill_poc"

    # /agentic or /crash-analysis (future PR) executed their
    # LLM-emitted exploit code and captured the bytes the code
    # produced. Not yet wired — placeholder for the planned
    # follow-up that adds runtime execution of the LLM artefact.
    LLM_EMIT_RUN = "llm_emit_run"

    # Operator supplied the witness directly — e.g., a known-good
    # PoC imported from a CVE writeup.
    MANUAL = "manual"


class WitnessOutcome(str, Enum):
    """What was observed when the target ran on the witness bytes.

    Normalised across pipelines so reporting / scoring can filter
    on outcome uniformly. Pipeline-specific detail (signal name,
    ASan content, stack hash, etc.) goes into ``Witness.outcome_detail``.
    """

    # Bytes were observed but the target wasn't executed against
    # them — e.g., a witness captured from a fuzz corpus before any
    # replay. Rare; most producers run the target.
    NOT_RUN = "not_run"

    # Target ran to completion without an obvious bug trigger.
    NO_OBVIOUS_EFFECT = "no_obvious_effect"

    # Target was killed by a signal (SIGSEGV, SIGABRT, SIGBUS, etc.).
    # ``outcome_detail['signal']`` carries the signal name.
    EXIT_SIGNAL = "exit_signal"

    # AddressSanitizer / UBSan / MSan emitted a diagnostic.
    # ``outcome_detail['sanitizer']`` and ``outcome_detail['report']``
    # carry the report.
    SANITIZER_REPORT = "sanitizer_report"

    # ExploitGym-style success marker: the witness achieved the
    # benchmark's defined success condition (typically reading a
    # flag file). Not yet emitted by any current pipeline.
    FLAG_CAPTURED = "flag_captured"

    # Producer doesn't know how the run terminated (e.g., a fuzz
    # crash file imported without replay data). The bytes exist;
    # the outcome doesn't.
    UNKNOWN = "unknown"


@dataclass
class Witness:
    """A typed record of "these bytes triggered this outcome on
    this target."

    Fields fall into four groups:

    * **Identity**: ``bytes_hash`` — SHA-256 of the bytes. Stable
      key for ``WitnessStore`` lookups and dedup across pipelines.
    * **Provenance**: ``source``, ``produced_by``, ``timestamp`` —
      who created this record, when, with what model / tool.
    * **Target binding**: ``target_binary_hash``,
      ``target_source_hash`` — bind the witness to a specific
      build. Optional; not every pipeline has both.
    * **Outcome**: ``observed_outcome`` (normalised label) plus
      ``outcome_detail`` (pipeline-specific blob).

    Witnesses are recorded by ``WitnessStore.put(witness, bytes_)``
    which also writes the bytes blob to disk. The store-write
    enforces that ``bytes_hash == sha256(bytes_)``.
    """

    bytes_hash: str
    source: WitnessSource
    observed_outcome: WitnessOutcome

    # Optional / pipeline-specific
    bytes_len: int = 0
    target_binary_hash: Optional[str] = None
    target_source_hash: Optional[str] = None
    outcome_detail: dict[str, Any] = field(default_factory=dict)
    produced_by: Optional[str] = None
    timestamp: datetime = field(
        default_factory=lambda: datetime.now(timezone.utc),
    )

    def __post_init__(self) -> None:
        # SHA-256 hex is 64 chars; reject silently-truncated hashes
        # so a downstream consumer relying on the hash for lookup
        # doesn't fail with a confusing "not found" later.
        if len(self.bytes_hash) != 64:
            raise ValueError(
                f"bytes_hash must be a 64-char SHA-256 hex digest, "
                f"got {len(self.bytes_hash)} chars: {self.bytes_hash[:16]!r}..."
            )
        # Verify the hash is actually hex.
        try:
            int(self.bytes_hash, 16)
        except ValueError as exc:
            raise ValueError(
                f"bytes_hash must be hex, got {self.bytes_hash[:16]!r}..."
            ) from exc

    def to_dict(self) -> dict[str, Any]:
        """JSON-safe serialisation. Datetime → ISO string, enums
        → str values, everything else passes through.

        Round-trip with ``Witness.from_dict`` is preserved for the
        canonical field set; unknown keys are ignored on load so
        future schema additions don't break old persisted manifests.
        """
        return {
            "bytes_hash": self.bytes_hash,
            "bytes_len": self.bytes_len,
            "source": self.source.value,
            "observed_outcome": self.observed_outcome.value,
            "target_binary_hash": self.target_binary_hash,
            "target_source_hash": self.target_source_hash,
            "outcome_detail": dict(self.outcome_detail),
            "produced_by": self.produced_by,
            "timestamp": self.timestamp.isoformat(),
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Witness":
        """Inverse of :meth:`to_dict`. Tolerant of extra keys —
        unknown fields are dropped silently so a future schema
        version writing extra metadata doesn't break old loaders."""
        ts_raw = data.get("timestamp")
        if isinstance(ts_raw, str):
            ts = datetime.fromisoformat(ts_raw)
        elif isinstance(ts_raw, datetime):
            ts = ts_raw
        else:
            ts = datetime.now(timezone.utc)

        return cls(
            bytes_hash=data["bytes_hash"],
            bytes_len=int(data.get("bytes_len", 0)),
            source=WitnessSource(data["source"]),
            observed_outcome=WitnessOutcome(data["observed_outcome"]),
            target_binary_hash=data.get("target_binary_hash"),
            target_source_hash=data.get("target_source_hash"),
            outcome_detail=dict(data.get("outcome_detail") or {}),
            produced_by=data.get("produced_by"),
            timestamp=ts,
        )


def compute_bytes_hash(data: bytes) -> str:
    """SHA-256 hex digest of ``data``.

    Single helper so all producers compute the hash consistently —
    avoids ``hashlib.sha256(data).hexdigest()`` boilerplate at
    every callsite and gives one place to audit the algorithm if
    we ever migrate (BLAKE3, SHA-3, etc.).
    """
    return hashlib.sha256(data).hexdigest()
