"""File exclusion logic — patterns, binary detection, generated file detection."""

import fnmatch
import os
from pathlib import Path
from typing import List

# Default exclude patterns — comprehensive list for clean inventory
DEFAULT_EXCLUDES = [
    # Test directories and files
    '*_test.*', 'test_*', '*_mock.*', 'mock_*', '*_spec.*',
    '__tests__/', 'tests/', 'test/', 'spec/', 'testing/',
    'fixtures/', '__fixtures__/', 'testdata/', 'test-data/',

    # Dependencies and vendor code
    'node_modules/', 'vendor/', 'third_party/', 'third-party/',
    'external/', 'deps/', 'dependencies/',

    # Python virtual environments and caches
    'venv/', '.venv/', 'env/', '.env/', 'virtualenv/',
    '__pycache__/', '.pytest_cache/', '.tox/', '.eggs/',
    '*.egg-info/', 'site-packages/',

    # Build outputs
    'dist/', 'build/', 'target/', 'out/', 'output/',
    'bin/', 'obj/', 'cmake-build-*/',

    # Version control
    '.git/', '.svn/', '.hg/', '.bzr/',

    # IDE and editor
    '.idea/', '.vscode/', '.vs/', '*.swp', '*.swo',

    # Generated/minified files
    '*.min.js', '*.min.css', '*.bundle.js', '*.bundle.css',
    '*.generated.*', '*.auto.*', '*_generated.*',
    '*_pb2.py', '*_pb2_grpc.py',  # Protobuf
    '*.pb.go', '*.pb.cc',  # Protobuf
    'generated/', 'gen/', 'autogen/',

    # Documentation
    'docs/', 'doc/', 'documentation/',

    # Examples and samples
    'examples/', 'example/', 'samples/', 'sample/', 'demo/',
]

# Subset of DEFAULT_EXCLUDES directory names that also legitimately occur as
# first-party package / source segments — a Spring sample under
# ``org/springframework/samples/…``, example code in ``examples/``, a ``doc``
# package, etc. Pruning these by basename at ANY depth silently drops
# first-party source from the inventory, a false negative for every downstream
# scanner. They are therefore pruned ONLY at the scan-root top level (where
# they're overwhelmingly throwaway demo / docs dirs); nested occurrences are
# kept and analysed. Unambiguous non-source dirs (node_modules, vendor, .git,
# build outputs, venvs, generated/, test dirs) are NOT here and keep pruning at
# any depth. Bare names (no trailing slash) to match a directory basename.
ROOT_ANCHORED_EXCLUDE_DIRS = frozenset({
    'examples', 'example', 'samples', 'sample', 'demo',
    'docs', 'doc', 'documentation',
})

# Markers that indicate a file is auto-generated (check first few lines)
GENERATED_MARKERS = [
    'auto-generated', 'autogenerated', 'automatically generated',
    'do not edit', 'do not modify', 'generated by', 'generated from',
    '@generated', '// code generated', '# generated', '/* generated',
    'this file was generated', 'machine generated',
]


def is_binary_file(filepath: Path, sample_size: int = 8192) -> bool:
    """Check if file is binary by looking for null bytes.

    Pre-fix the check sampled only the first ``sample_size`` bytes.
    Files with a long ASCII prefix followed by binary content
    (polyglots, malformed source generated by a buggy emitter,
    target-repo files with a text header documenting an embedded
    binary blob, or LLM-generated synthetic-vuln test fixtures
    that paste a large header) escaped detection — the inventory
    then tried to extract functions from a binary tail and
    tree-sitter spent CPU on garbage before erroring.

    Sample BOTH ends: the original head sample plus a tail sample
    of the same size when the file is larger than 2 * sample_size.
    Files smaller than 2 * sample_size are fully covered by the
    head sample alone (the tail would overlap, no extra coverage).
    Single seek + read for the tail keeps wallclock minimal.
    """
    try:
        with open(filepath, 'rb') as f:
            chunk = f.read(sample_size)
            if b'\x00' in chunk:
                return True
            # Tail probe — only worth doing when the file is large
            # enough that the head sample didn't already cover it.
            try:
                f.seek(0, 2)  # SEEK_END
                size = f.tell()
            except OSError:
                return False
            if size > 2 * sample_size:
                f.seek(size - sample_size)
                tail = f.read(sample_size)
                if b'\x00' in tail:
                    return True
            return False
    except (IOError, OSError):
        return True  # Treat unreadable as binary


def is_generated_file(content: str, check_lines: int = 10) -> bool:
    """Check if file appears to be auto-generated.

    Comment-anchored: each marker must appear inside a COMMENT line
    (lines starting with `#`, `//`, `/*`, `*`, `--`, `<!--`,
    optionally with leading whitespace) within the first
    `check_lines` lines.

    Pre-fix the substring scan checked the lowercased header
    text without comment-anchoring, so:

    * A regular Python file containing the string `"automatically
      generated"` in a docstring, error message, or test fixture
      (`"this script generates the report automatically generated
      from..."`) was wrongly classified as auto-generated and
      excluded from the inventory. Real callers had analysis-
      target files dropped silently — coverage stats wrong, sinks
      missed.
    * A SARIF rule description that mentioned "do not edit"
      (e.g. flagging hardcoded credentials with the message
      "do not edit; this credential ...") triggered the marker
      from inside the SARIF JSON.
    * A test file documenting a generator's behaviour ("verify
      that generated files contain the auto-generated marker")
      excluded itself even though it was a test, not generated.

    Anchor to comments: the marker must be inside a recognisable
    comment to count. Generators emit their markers in comment
    headers; the substring-only check matched any prose mention.
    """
    lines = content.split('\n', check_lines)[:check_lines]
    # Comment-line shapes for the languages we extract from.
    # `re.match` against the leading-whitespace + comment-start
    # pattern. If the line isn't a comment, skip it for marker
    # matching (but still consider it as "we've seen check_lines
    # of content"). The comment-prefix list covers C/C++/Java
    # (`//`, `/*`, ` *` continuation), Python/shell/Ruby (`#`),
    # SQL/Lua (`--`), and HTML/XML (`<!--`).
    import re as _re
    comment_re = _re.compile(r'^\s*(#|//|/\*|\*|--|<!--)')
    for raw in lines:
        if not comment_re.match(raw):
            continue
        lowered = raw.lower()
        for marker in GENERATED_MARKERS:
            if marker in lowered:
                return True
    return False


def should_exclude(filepath: str, exclude_patterns: List[str]) -> bool:
    """Check if file should be excluded based on patterns.

    Returns True if the file matches any exclusion pattern.
    """
    filepath_lower = filepath.lower()
    path_parts_lower = filepath_lower.split(os.sep)

    for pattern in exclude_patterns:
        pattern_lower = pattern.lower()
        # Directory pattern (ends with /)
        if pattern.endswith('/'):
            dir_name = pattern_lower[:-1]
            # When the directory pattern contains glob metacharacters
            # (e.g. ``*.egg-info/``, ``cmake-build-*/``), match each path
            # component via fnmatch. Plain ``in`` would only catch a literal
            # path segment named ``*.egg-info``, which never exists.
            if any(c in dir_name for c in "*?["):
                if any(fnmatch.fnmatch(part, dir_name) for part in path_parts_lower):
                    return True
            elif dir_name in ROOT_ANCHORED_EXCLUDE_DIRS:
                # First-party-collision-prone name (examples/ samples/ docs/ …):
                # only a TOP-LEVEL dir of this name is a throwaway demo/docs dir.
                # A nested occurrence is a package/source segment, so matching it
                # anywhere would silently exclude first-party source. Anchor to
                # the first path component (mirrors the walk-time prune).
                if path_parts_lower and path_parts_lower[0] == dir_name:
                    return True
            elif dir_name in path_parts_lower:
                return True
        # Glob pattern
        elif '*' in pattern:
            if fnmatch.fnmatch(os.path.basename(filepath_lower), pattern_lower):
                return True
            if fnmatch.fnmatch(filepath_lower, pattern_lower):
                return True
        # Exact filename or path segment match
        elif pattern_lower in path_parts_lower or pattern_lower == os.path.basename(filepath_lower):
            return True

    return False


def match_exclusion_reason(filepath: str, exclude_patterns: List[str]) -> tuple:
    """Like should_exclude but returns (excluded: bool, reason, pattern_matched).

    Used for exclusion recording in the inventory.
    """
    filepath_lower = filepath.lower()
    path_parts_lower = filepath_lower.split(os.sep)

    for pattern in exclude_patterns:
        pattern_lower = pattern.lower()
        if pattern.endswith('/'):
            dir_name = pattern_lower[:-1]
            if any(c in dir_name for c in "*?["):
                if any(fnmatch.fnmatch(part, dir_name) for part in path_parts_lower):
                    return True, "pattern_match", pattern
            elif dir_name in ROOT_ANCHORED_EXCLUDE_DIRS:
                # Anchor first-party-collision-prone names to the top level
                # (see should_exclude) so nested package/source segments named
                # samples/ examples/ docs/ … are not silently excluded.
                if path_parts_lower and path_parts_lower[0] == dir_name:
                    return True, "pattern_match", pattern
            elif dir_name in path_parts_lower:
                return True, "pattern_match", pattern
        elif '*' in pattern:
            if fnmatch.fnmatch(os.path.basename(filepath_lower), pattern_lower):
                return True, "pattern_match", pattern
            if fnmatch.fnmatch(filepath_lower, pattern_lower):
                return True, "pattern_match", pattern
        elif pattern_lower in path_parts_lower or pattern_lower == os.path.basename(filepath_lower):
            return True, "pattern_match", pattern

    return False, None, None
