import type { LogEntry, Tool } from "@/types/tools";

export const MOCK_TOOLS: Tool[] = [
    {
        id: "vuln_scanner",
        name: "Local Vulnerability Scanner",
        description: "Local port scan and OS checks on the specified host.",
        category: "Local",
        risk: "low",
        status: "ready",
        inputs: [
            { key: "target", label: "Target", placeholder: "127.0.0.1", required: false, type: "text" },
        ],
        tags: ["lab", "safe"],
    },
    {
        id: "network_scanner",
        name: "Network Scanner",
        description: "ARP discovery for local subnet devices.",
        category: "Network",
        risk: "low",
        status: "ready",
        inputs: [
            { key: "target", label: "Target CIDR", placeholder: "192.168.1.0/24", required: false, type: "text" },
        ],
    },
    {
        id: "network_recon",
        name: "Network Recon",
        description: "Port scan and light service enumeration (private targets only).",
        category: "Network",
        risk: "medium",
        status: "ready",
        inputs: [
            { key: "target", label: "Target IP/CIDR", placeholder: "192.168.1.10", required: true, type: "text" },
        ],
    },
    {
        id: "osint_recon",
        name: "OSINT Recon",
        description: "Domain and web metadata collection for defensive analysis.",
        category: "OSINT",
        risk: "low",
        status: "ready",
        inputs: [
            { key: "domain", label: "Domain or URL", placeholder: "example.com", required: true, type: "text" },
        ],
    },
    {
        id: "packet_sniffer",
        name: "Packet Sniffer",
        description: "Local packet capture summary (requires admin/root).",
        category: "Network",
        risk: "medium",
        status: "ready",
        inputs: [
            { key: "duration", label: "Capture Duration (sec)", placeholder: "20", required: false, type: "number" },
        ],
    },
    {
        id: "ip_scanner",
        name: "IP Scanner",
        description: "IP lookup with optional private-target port scan.",
        category: "OSINT",
        risk: "low",
        status: "ready",
        inputs: [
            { key: "target", label: "Target IP", placeholder: "192.168.1.10", required: false, type: "text" },
        ],
    },
    {
        id: "mobile_security",
        name: "Mobile Security",
        description: "APK static analysis and basic TLS/API checks.",
        category: "Mobile",
        risk: "low",
        status: "ready",
        inputs: [
            { key: "file_path", label: "APK Path", placeholder: "C:/path/app.apk", required: false, type: "path" },
            { key: "domain", label: "Domain", placeholder: "api.example.com", required: false, type: "text" },
        ],
    },
    {
        id: "malware_analyzer",
        name: "Malware Analyzer",
        description: "Static file analysis (hashes, entropy, PE metadata).",
        category: "SOC",
        risk: "medium",
        status: "ready",
        inputs: [
            { key: "file_path", label: "File Path", placeholder: "C:/path/sample.bin", required: true, type: "path" },
        ],
    },
    {
        id: "threat_hunting",
        name: "Threat Hunting",
        description: "IOC lookup for indicators or files.",
        category: "SOC",
        risk: "low",
        status: "ready",
        inputs: [
            { key: "target", label: "Indicator", placeholder: "indicator", required: false, type: "text" },
            { key: "file_path", label: "File Path", placeholder: "C:/path/log.txt", required: false, type: "path" },
        ],
    },
    {
        id: "honeypot_system",
        name: "Honeypot System",
        description: "Run local honeypots on safe ports and capture events.",
        category: "SOC",
        risk: "medium",
        status: "ready",
        inputs: [
            { key: "duration", label: "Duration (sec)", placeholder: "30", required: false, type: "number" },
        ],
    },
    {
        id: "report_generator",
        name: "Report Generator",
        description: "Generate HTML/JSON/Markdown reports from input data.",
        category: "Reports",
        risk: "low",
        status: "ready",
        inputs: [
            { key: "file_path", label: "Input JSON", placeholder: "C:/path/report.json", required: true, type: "path" },
        ],
    },
    {
        id: "ai_threat",
        name: "AI Threat Detection",
        description: "Anomaly detection demo on synthetic events.",
        category: "Advanced",
        risk: "low",
        status: "ready",
        tags: ["demo"],
    },
    {
        id: "zero_trust",
        name: "Zero Trust Framework",
        description: "Policy engine simulation for access decisions.",
        category: "Advanced",
        risk: "low",
        status: "ready",
        tags: ["demo"],
    },
    {
        id: "sql_injection_scanner",
        name: "SQL Injection Scanner",
        description: "Automated SQL injection vulnerability detection for web applications.",
        category: "Web",
        risk: "medium",
        status: "ready",
        inputs: [
            { key: "target_url", label: "Target URL", placeholder: "http://example.com/page?id=1", required: true, type: "text" },
            { key: "method", label: "HTTP Method", placeholder: "GET", required: false, type: "text" },
        ],
        tags: ["web", "injection", "sqli"],
    },
    {
        id: "xss_detector",
        name: "XSS Vulnerability Detector",
        description: "Cross-Site Scripting (XSS) vulnerability scanner for web applications.",
        category: "Web",
        risk: "medium",
        status: "ready",
        inputs: [
            { key: "target_url", label: "Target URL", placeholder: "http://example.com/search", required: true, type: "text" },
            { key: "payload_type", label: "Payload Type", placeholder: "reflected", required: false, type: "text" },
        ],
        tags: ["web", "xss", "injection"],
    },
    {
        id: "ssl_tls_analyzer",
        name: "SSL/TLS Security Analyzer",
        description: "Comprehensive SSL/TLS configuration and certificate security analysis.",
        category: "Network",
        risk: "low",
        status: "ready",
        inputs: [
            { key: "target_host", label: "Target Host", placeholder: "example.com:443", required: true, type: "text" },
        ],
        tags: ["ssl", "tls", "crypto", "certificate"],
    },
    {
        id: "dns_enumeration",
        name: "DNS Enumeration Tool",
        description: "Advanced DNS reconnaissance and subdomain discovery.",
        category: "OSINT",
        risk: "low",
        status: "ready",
        inputs: [
            { key: "domain", label: "Target Domain", placeholder: "example.com", required: true, type: "text" },
            { key: "wordlist", label: "Wordlist", placeholder: "common", required: false, type: "text" },
        ],
        tags: ["dns", "recon", "subdomain"],
    },
    {
        id: "wireless_audit",
        name: "Wireless Security Audit",
        description: "WiFi network security assessment and vulnerability detection.",
        category: "Network",
        risk: "medium",
        status: "ready",
        inputs: [
            { key: "interface", label: "Network Interface", placeholder: "wlan0", required: false, type: "text" },
            { key: "duration", label: "Scan Duration (sec)", placeholder: "60", required: false, type: "number" },
        ],
        tags: ["wifi", "wireless", "802.11"],
    },
    {
        id: "web_scanner",
        name: "Web App Scanner",
        description: "Blocked: offensive web vulnerability testing.",
        category: "Web",
        risk: "high",
        status: "blocked",
        blocked_reason: "Offensive testing is disabled in defensive-only mode.",
    },
    {
        id: "password_auditor",
        name: "Password Auditor",
        description: "Blocked: credential testing is not permitted.",
        category: "Audit",
        risk: "high",
        status: "blocked",
        blocked_reason: "Credential cracking is disabled.",
    },
    {
        id: "c2_simulator",
        name: "C2 Simulator",
        description: "Blocked: offensive simulation not permitted.",
        category: "Exploit",
        risk: "high",
        status: "blocked",
        blocked_reason: "Offensive simulation is disabled.",
    },
];

const DEFAULT_LOG_SCRIPT: Array<Pick<LogEntry, "level" | "message">> = [
    { level: "info", message: "Initializing defensive workflow..." },
    { level: "info", message: "Collecting local telemetry..." },
    { level: "success", message: "Scan complete. No critical issues detected." },
];

const MOCK_LOG_SCRIPTS: Record<string, Array<Pick<LogEntry, "level" | "message">>> = {
    vuln_scanner: [
        { level: "info", message: "Starting local checks on target host." },
        { level: "info", message: "Enumerating open ports and services." },
        { level: "warning", message: "Legacy protocol detected (TLS 1.0 enabled)." },
        { level: "success", message: "Baseline hardening recommendations generated." },
    ],
    network_scanner: [
        { level: "info", message: "Running ARP discovery for local subnet." },
        { level: "info", message: "Discovered 6 active devices." },
        { level: "success", message: "Exported asset inventory snapshot." },
    ],
    network_recon: [
        { level: "info", message: "Executing quick network reconnaissance." },
        { level: "info", message: "Detected SSH service on 10.10.10.15." },
        { level: "success", message: "Service summary complete." },
    ],
    osint_recon: [
        { level: "info", message: "Collecting WHOIS and DNS metadata." },
        { level: "info", message: "TLS certificate details captured." },
        { level: "success", message: "OSINT report generated." },
    ],
    packet_sniffer: [
        { level: "info", message: "Starting packet capture on local interface." },
        { level: "info", message: "Captured 120 packets (summary only)." },
        { level: "success", message: "Capture stopped and summarized." },
    ],
    mobile_security: [
        { level: "info", message: "Parsing APK manifest and permissions." },
        { level: "warning", message: "Sensitive permissions detected: READ_SMS." },
        { level: "success", message: "Mobile security report ready." },
    ],
    malware_analyzer: [
        { level: "info", message: "Calculating file hashes and entropy." },
        { level: "info", message: "No known signatures matched." },
        { level: "success", message: "Static analysis complete." },
    ],
    threat_hunting: [
        { level: "info", message: "Checking indicators against intel sources." },
        { level: "warning", message: "Indicator hit detected in logs." },
        { level: "success", message: "Hunt summary finalized." },
    ],
    honeypot_system: [
        { level: "info", message: "Starting honeypot listeners on safe ports." },
        { level: "info", message: "Captured 3 inbound connection attempts." },
        { level: "success", message: "Honeypot session summary ready." },
    ],
    report_generator: [
        { level: "info", message: "Rendering report templates." },
        { level: "success", message: "Report generated successfully." },
    ],
    ai_threat: [
        { level: "info", message: "Scoring synthetic anomalies." },
        { level: "success", message: "AI detection demo complete." },
    ],
    zero_trust: [
        { level: "info", message: "Evaluating access policies." },
        { level: "success", message: "Zero trust simulation finished." },
    ],
    sql_injection_scanner: [
        { level: "info", message: "Starting SQL injection vulnerability scan..." },
        { level: "info", message: "Testing GET parameters for SQL injection." },
        { level: "warning", message: "Potential SQL injection vulnerability detected in 'id' parameter." },
        { level: "info", message: "Testing error-based SQL injection payloads." },
        { level: "warning", message: "Database error messages exposed - security risk." },
        { level: "success", message: "SQL injection scan complete. 2 vulnerabilities found." },
    ],
    xss_detector: [
        { level: "info", message: "Initializing XSS vulnerability scanner..." },
        { level: "info", message: "Testing reflected XSS in search parameter." },
        { level: "warning", message: "Reflected XSS vulnerability detected!" },
        { level: "info", message: "Testing stored XSS in user input fields." },
        { level: "success", message: "XSS scan complete. 1 reflected XSS found." },
    ],
    ssl_tls_analyzer: [
        { level: "info", message: "Connecting to target host on port 443..." },
        { level: "info", message: "Analyzing SSL/TLS configuration." },
        { level: "success", message: "TLS 1.3 supported - excellent!" },
        { level: "info", message: "Checking certificate validity and chain." },
        { level: "warning", message: "Certificate expires in 45 days - renewal recommended." },
        { level: "info", message: "Testing cipher suites and protocols." },
        { level: "warning", message: "Weak cipher suite detected: TLS_RSA_WITH_3DES_EDE_CBC_SHA." },
        { level: "success", message: "SSL/TLS analysis complete. Overall grade: B+" },
    ],
    dns_enumeration: [
        { level: "info", message: "Starting DNS enumeration for target domain..." },
        { level: "info", message: "Querying NS, A, AAAA, MX, TXT records." },
        { level: "success", message: "Found 4 nameservers." },
        { level: "info", message: "Performing subdomain brute-force with wordlist." },
        { level: "success", message: "Discovered subdomain: www.example.com" },
        { level: "success", message: "Discovered subdomain: mail.example.com" },
        { level: "success", message: "Discovered subdomain: api.example.com" },
        { level: "info", message: "Checking for zone transfer vulnerability." },
        { level: "success", message: "DNS enumeration complete. 3 subdomains found." },
    ],
    wireless_audit: [
        { level: "info", message: "Initializing wireless security audit..." },
        { level: "info", message: "Setting network interface to monitor mode." },
        { level: "info", message: "Scanning for nearby WiFi networks..." },
        { level: "success", message: "Found 12 wireless networks in range." },
        { level: "warning", message: "Open network detected: 'FreeWiFi' - no encryption!" },
        { level: "warning", message: "WEP encryption detected on 'OldRouter' - highly insecure." },
        { level: "info", message: "Analyzing WPA2/WPA3 security configurations." },
        { level: "success", message: "Wireless audit complete. 2 security issues found." },
    ],
};

export function buildMockLogs(toolId: string): LogEntry[] {
    const script = MOCK_LOG_SCRIPTS[toolId] || DEFAULT_LOG_SCRIPT;
    const start = Math.floor(Date.now() / 1000);
    return script.map((entry, index) => ({
        timestamp: start + index,
        level: entry.level,
        message: entry.message,
    }));
}
